---
title: 'Tweets Analysis'
output: github_document
editor_options: 
  chunk_output_type: console
---
## Tweets Analysis

**Month counts**: Show the counts of tweets in each month.

```{r}
library(tidyverse)
library(tidytext)
library(knitr)
#Call libraries
library(NLP)
library(ROAuth)
install.packages("topicmodels")
library(syuzhet)
library(tm)
library(SnowballC)
library(stringi)
library(topicmodels)

tweets_2019_state<-read_csv("data/clean_local_time_2019-03_2020-02_bbox_state_level.csv")

#Preprocess data
tweets_2019_state_text<- tweets_2019_state$text

#Replace blank space ("rt")
tweets_2019_state_text <- gsub("rt", "", tweets_2019_state_text)

# Replace @UserName
tweets_2019_state_text <- gsub("@\\w+", "", tweets_2019_state_text)


# Remove punctuation
tweets_2019_state_text <- gsub("[[:punct:]]", "", tweets_2019_state_text)

# Remove links
tweets_2019_state_text <- gsub("http\\w+", "", tweets_2019_state_text)

# Remove tabs
tweets_2019_state_text <- gsub("[ |\t]{2,}", "", tweets_2019_state_text)

# Remove blank spaces at the beginning
tweets_2019_state_text <- gsub("^ ", "", tweets_2019_state_text)

# Remove blank spaces at the end
tweets_2019_state_text <- gsub(" $", "", tweets_2019_state_text)

#Create corpus
tweets_2019_state_text_corpus=Corpus(VectorSource(tweets_2019_state_text))

#Clean up by removing stop words
tweets_2019_state_text_corpus <- tm_map(tweets_2019_state_text_corpus, removeWords,stopwords(kind = 'en'))


```


**Histogram of counts in each month**: Sentiment Analysis

```{r}
#Getting emotions using in-built function
mysentiment_tweets<-get_nrc_sentiment((tweets_2019_state_text))

#Calculating total score for each sentiment
Sentimentscores_tweets<-data.frame(colSums(mysentiment_tweets[,]))

names(Sentimentscores_tweets)<-"Score"
Sentimentscores_tweets<-cbind("sentiment"=rownames(Sentimentscores_tweets),Sentimentscores_tweets)
rownames(Sentimentscores_tweets)<-NULL

```


```{R}
library(ggplot2)
ggplot(data=Sentimentscores_tweets,aes(x=sentiment,y=Score))+geom_bar(aes(fill=sentiment),stat = "identity")+
  theme(legend.position="none")+
  xlab("Sentiments")+ylab("scores")+ggtitle("Manchester United")

```

```{R}
write.csv(Sentimentscores_tweets, "data/sentimentscores_tweets_states.csv")
```