---
title: 'Tweets Analysis'
output: github_document
editor_options: 
  chunk_output_type: console
---
## Tweets Analysis

**Month counts**: Show the counts of tweets in each month.

```{r}
library(tidyverse)
library(tidytext)
library(knitr)
#Call libraries
library(NLP)
library(ROAuth)
#install.packages("topicmodels")
library(syuzhet)
library(tm)
library(SnowballC)
library(stringi)
library(topicmodels)

tweets_2019_state<-read_csv("data/TweetTopicState_1920.csv")

#Preprocess data
tweets_2019_state_text<-tweets_2019_state$tweet

#Replace blank space ("rt")
tweets_2019_state_text <- gsub("rt", "", tweets_2019_state_text)

# Replace @UserName
tweets_2019_state_text <- gsub("@\\w+", "", tweets_2019_state_text)


# Remove punctuation
tweets_2019_state_text <- gsub("[[:punct:]]", "", tweets_2019_state_text)

# Remove links
tweets_2019_state_text <- gsub("http\\w+", "", tweets_2019_state_text)

# Remove tabs
tweets_2019_state_text <- gsub("[ |\t]{2,}", "", tweets_2019_state_text)

# Remove blank spaces at the beginning
tweets_2019_state_text <- gsub("^ ", "", tweets_2019_state_text)

# Remove blank spaces at the end
tweets_2019_state_text <- gsub(" $", "", tweets_2019_state_text)

#Create corpus
tweets_2019_state_text_corpus=Corpus(VectorSource(tweets_2019_state_text))

#Clean up by removing stop words
tweets_2019_state_text_corpus <- tm_map(tweets_2019_state_text_corpus, removeWords,stopwords(kind = 'en'))


```


**Histogram of counts in each month**: Sentiment Analysis

```{r}
#Getting emotions using in-built function
mysentiment_tweets<-get_nrc_sentiment((tweets_2019_state_text))

#add state information
mysentiment_tweets_states<-cbind(mysentiment_tweets,state=tweets_2019_state$NAME,month=tweets_2019_state$Month,topic=tweets_2019_state$dominant_topic,tweets=tweets_2019_state$tweet)
```


```{R}
#Calculating total score for each sentiment
Sentimentscores_tweets<-mysentiment_tweets_states%>%
  group_by(state,month)%>%
  summarise(joy=sum(joy),anger=sum(anger),anticipation=sum(anticipation),disgust=sum(disgust),fear=sum(fear),sadness=sum(sadness),surprise=sum(surprise),trust=sum(trust),negative=sum(negative),positive=sum(positive),topic=sum(topic))

write.csv(mysentiment_tweets_states,"data/alltweet1_sentimentscores_topic_states_1920.csv",row.names=FALSE)

write.csv(Sentimentscores_tweets,"data/groupbytweet_sentimentscores_topic_statesmonth_1920.csv",row.names=FALSE)
sentimentscores_states<-read_csv("data/groupbytweet_sentimentscores_topic_statesmonth_1920.csv")
sentimentscores_states_long<-sentimentscores_states%>%
  pivot_longer(topic,
               names_to = "Topic",
               values_to = "Score")

library(ggplot2)
ggplot(data=sentimentscores_states_long,aes(x=sentiment,y=Score))+geom_bar(aes(fill=sentiment),stat = "identity")+
  theme(legend.position="bottom",axis.text.x=element_blank())+ylab("Scores")+
  facet_wrap(~state,scales="free",ncol=6)

```